### ISSUE TITLE
Teams With One Player Should Be Automatically Disqualified and Replaced on Tournament Start

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#104]
Teams with one player were able to register for the recent ForgeHub 2v2 tournament however when the tournament started, their team mate never showed up.  This is a guaranteed loss, if a team only has one player, they will most likely not participate in the event.  We shouldn't allow this to occur either.

Enhancement:
- Teams with only one player will be disqualified / not seeded in tournament if 2nd team mate does not join before tournament start time.
- Teams on 'standby' will replace teams with 'pending approval' status when tournament starts.
- Messages automatically sent to teams on standby confirming their registration

**Comment by JakeBooher** [comment]
I isn't currently possible to join a tournament unless your team already has the required number of users. If you're able to replicate this again somehow do let me know with reproduction steps
