### ISSUE TITLE
Match Results Require Both Teams To Submit Scores

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#106]
Both teams are required to submit match results to update bracket information.  Sometimes teams prematurely quit out of a match if they are losing and are unable to make a come back.  The losing team that quit out of the match will most likely not submit their scores on battlepro.  In these situations, a tournament will not move forward due to the requirement for score reporting from both teams.  Sometimes, teams simply do not report scoring since they believe the winning team will do so on their behalf.

**Enhancement:**
- Do not require both teams to submit scoring.  If results are improperly reported, teams may file a 'dispute', which will auto create a conversation between the host and the two teams involved.
- Allow match results to be posted by a single team (winner or loser).

**Comment by kylerc** [comment]
@NikAlexander This shouldn't be too hard to implement.  I've got some changes to brackets I'm in the middle of for multiple stages, but once that's finished and bracket generation is stable again I'll be able to add this as well.  @JakeBooher this will take some changes on your end as well.
