### ISSUE TITLE
Implement Credits System

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#112]
We have planned on implementing a credit system so that players engaging in wagered matches can supply monetary wagers.  Tournament prizing may also be immediately distributed through a 'smart contract' system where winners are provided with credits as the tournament is finished.  Quite some time ago, @mikecreuzer said Audentio owns a XenForo add-on for credits which would be great to use.

**Comment by JakeBooher** [comment]
This was already implemented quite some time ago
