### ISSUE TITLE
Matches: Team Name Chosen Already In Use

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#114]
When users attempt to join a Match and a team name that mirrors their username is in existence, it prevents them from joining a Match.  The following error notification will be provided:

**THE FOLLOWING ERROR OCCURED:**
_"The team name you have chosen is already in use."_

**Details:**
- User [Audentio ](https://www.battlepro.com/members/audentio.2/)created a 2v2 team called [Audentio](https://www.battlepro.com/teams/audentio.39/view), the same spelling as the username.
- Audentio attempts to join [1v1 wagered match](https://www.battlepro.com/matches/1v1-halo-5.24/view) created by Warholic
- Audentio is unable to join the match and received error notification.

**Solution:**
- Do not allow users to create teams that are the same as registered usernames.  Usernames should be saved for Solo Team creation only.  
- Solo teams should be automatically created (same as username) when a user attempts to join a solo tournament or match.

**Error Report:**
![join match audentio](https://user-images.githubusercontent.com/6005869/30138172-d53a36b8-9334-11e7-961f-fc890711f037.JPG)

**Comment by JakeBooher** [comment]
> Do not allow users to create teams that are the same as registered usernames. Usernames should be saved for Solo Team creation only.

Unfortunately this won't be reliable as someone could register after a team was created with the same name, so we'd also need to prevent users from registering with the name of an existing team (and as an extension of that we also have to prevent admins from changing the username of a user to the name of an existing team)

> Solo teams should be automatically created (same as username) when a user attempts to join a solo tournament or match.

This is how it currently behaves

I think a better solution could be either:

1. We allow solo teams to have the same name as an existing team
2. We completely remove the requirement for a unique team name

I think 1 would probably be the most reliable
