### ISSUE TITLE
invite button should give error, or some kind of indication of why it cant be clicked

### ISSUE THREAD

**Issue by Ian-Hitt** [BattlePro/battlepro-issues#116]
<img width="510" alt="screen shot 2017-09-14 at 1 23 52 pm" src="https://user-images.githubusercontent.com/15836384/30446857-f8809a42-994f-11e7-85af-f0d5525e7e19.png">

http://test.battlepro.com/teams/exlbrs.1/view

**Comment by JakeBooher** [comment]
That shouldn't be a button, it's indicating that the team is invite only and that you can't join or apply to join it
