### ISSUE TITLE
create tournament, if only 1 title, auto select and dont display the field

### ISSUE THREAD

**Issue by Ian-Hitt** [BattlePro/battlepro-issues#119]
<img width="682" alt="screen shot 2017-09-15 at 10 06 31 am" src="https://user-images.githubusercontent.com/15836384/30490074-8e0443e4-99fe-11e7-8b05-f576a9d175a5.png">

http://test.battlepro.com/admin.php?templates/bp_createtournament_createtournament.785/edit&style_id=6

https://www.test.battlepro.com/matches/add

**Comment by kylerc** [comment]
I believe the auto-select was completed a little while back.  It does still show the fields, but I think that's potentially useful for users still.
