### ISSUE TITLE
games without titles create duplicate-ish filter items. 

### ISSUE THREAD

**Issue by Ian-Hitt** [BattlePro/battlepro-issues#121]
<img width="517" alt="screen shot 2017-09-18 at 1 25 11 pm" src="https://user-images.githubusercontent.com/15836384/30557713-d05024d4-9c74-11e7-9c7a-9a89169c9465.png">

**Comment by JakeBooher** [comment]
This is intentional, You can filter by title or game so you could search for all Call of Duty games, or specifically Call of Duty 2

**Comment by Ian-Hitt** [comment]
@JakeBooher Yes, i know it is intentional, but it will appear as a bug to users. if a game has only one title, then it does not need to filter by both title as well as franchise.
