### ISSUE TITLE
Matches without a banner used to show game logo

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#123]
<img width="501" alt="screen shot 2017-09-18 at 2 05 18 pm" src="https://user-images.githubusercontent.com/1217271/30559503-7d8002a0-9c7a-11e7-8245-505ee6fb7518.png">

**Comment by Ian-Hitt** [comment]
@mikecreuzer it is using a loop, and adding a class like so: ```bp_tournamentBanner bp_tournamentBanner--iconBanner bp_icon bp-gameLogo-7```

Needs add-on update to support image for game. That way when there is no image in the db, we can set a default.

**Comment by Ian-Hitt** [comment]
requires: https://github.com/BattlePro/battlepro-issues/issues/122

**Comment by Ian-Hitt** [comment]
@mikecreuzer Can't don't have anything to check, so can't set a default logo

using this currently

```			<xen:if is="{$tournament.has_banner}">
				<span class="bp_tournamentBanner bp_tournamentBanner--imageBanner" style="background-image: url(data/battlepro/tournament/banner-{$tournament.tournament_id}.jpg)"></span>
			<xen:else />
				<span class="bp_tournamentBanner bp_tournamentBanner--iconBanner bp_icon bp-gameLogo-{$tournament.game_id}"></span>
			</xen:if>
```

**Comment by Ian-Hitt** [comment]
it sets a default logo for games that have a logo uploaded, but no way to know if one is uploaded or not
