### ISSUE TITLE
Update Text Logo

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#13]
One of the stipulations in our trademark settlement was to drop the double word mark (battle pro) and to only keep the single word mark (battlepro). I think this is a good time to update the font type and color scheme.

**Font:** QTypeSquare-Medium Regular (BOLD and customized with 85% letter height and 95% letter width)
**Photoshop Color #** 1fceef

**Comment by NikAlexander** [comment]
![bphome](https://user-images.githubusercontent.com/6005869/28992171-8ff7108e-7963-11e7-9a41-622d01705b47.jpg)
![bpfont](https://user-images.githubusercontent.com/6005869/28992170-8ff4e3cc-7963-11e7-9924-ab1e6d4a72eb.jpg)
![battleprohome](https://user-images.githubusercontent.com/6005869/28992172-900343cc-7963-11e7-978c-4dc7184549d8.JPG)

**Comment by nikkiradloff** [comment]
![bp-full-logo](https://user-images.githubusercontent.com/15836402/30436973-18d28db8-9933-11e7-83fc-d8fe47da0959.png)
