### ISSUE TITLE
My Events: weird flash/jump when switching between tabs

### ISSUE THREAD

**Issue by nikkiradloff** [BattlePro/battlepro-issues#130]
![events_jump](https://user-images.githubusercontent.com/15836402/30602899-924f07ec-9d2b-11e7-862e-d0d85910d403.gif)

**Comment by kylerc** [comment]
Not currently seeing this.  I'm going to assume it was caused at the time by a JS issue on the page which resulted in switching tabs doing a full refresh.  If it comes back repoen.
