### ISSUE TITLE
Creating tourny/match game choose: active state fill white

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#132]
Currently color doesnt change, just make it white.

**Comment by Ian-Hitt** [comment]
<img width="731" alt="screen shot 2017-09-26 at 2 00 22 pm" src="https://user-images.githubusercontent.com/15836384/30878727-0d343864-a2c3-11e7-90db-2fe5c6ada3dc.png">

**Comment by Ian-Hitt** [comment]
are you talking about that?

**Comment by mikecreuzer** [comment]
Yes but for games we don't have a color for. Just make white the default fill.

**Comment by Ian-Hitt** [comment]
requires https://github.com/BattlePro/battlepro-issues/issues/122

**Comment by mikecreuzer** [comment]
You did this already.
