### ISSUE TITLE
change loop to only show featured titles with images set

### ISSUE THREAD

**Issue by nikkiradloff** [BattlePro/battlepro-issues#134]
<img width="466" alt="screen shot 2017-09-20 at 9 14 09 am" src="https://user-images.githubusercontent.com/15836402/30648702-4a175448-9de4-11e7-8583-6c643d6e9e9f.png">

**Comment by Ian-Hitt** [comment]
requires add-on development https://github.com/BattlePro/battlepro-issues/issues/122

**Comment by Ian-Hitt** [comment]
need to check if game title has an image, if not, don't display

**Comment by Ian-Hitt** [comment]
in template: "bp_gameChooser" replace

```
					<a href="{$bp_titleHref}" class="bp_gameChooser--item">
						<div class="bp_gameChooser--overlay">
							<span class="bpro_game_title_name">{$title.title_name}</span>
							<span class="bpro_game_title_all">See all Games</span>
						</div>
						<img src="@imagePath/battlepro/media/game-chooser/{$title.game_title_id}.jpg">
					</a>
````

with the image associated with the game title in the DB
