### ISSUE TITLE
loop through game_titles, if image, use image, else use text

### ISSUE THREAD

**Issue by nikkiradloff** [BattlePro/battlepro-issues#135]
<img width="774" alt="screen shot 2017-09-20 at 9 17 36 am" src="https://user-images.githubusercontent.com/15836402/30648907-c5c2c258-9de4-11e7-8bda-edb7c608bde6.png">

Error page:
http://test.battlepro.com/tournaments/counter-stroke-global-offensive

**Comment by Ian-Hitt** [comment]
Requires add-on development @JakeBooher

**Comment by Ian-Hitt** [comment]
https://github.com/BattlePro/battlepro-issues/issues/122

**Comment by Ian-Hitt** [comment]
@mikecreuzer just using this atm because game titles dont have images, only franchises

```<img src="@imagePath/battlepro/media/game-chooser/{$title.game_title_id}.jpg">```

**Comment by JakeBooher** [comment]
We'll be resolving this with #167
