### ISSUE TITLE
Repace dropkick JS

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#137]
- [ ] Remove dropkick and any hacky CSS we had to add
- [ ] Load in bootstrap 4 form css, start using it but do not need to change everywhere
- [ ] Style <selects> with emphasis on webkit. Its not worth having broken selects just so they are dark themed. Can leave white for older browsers.

**Comment by Ian-Hitt** [comment]
@mikecreuzer Bootstrap select menus will have the same problem we are currently having. they will not work with overflow: hidden;
<img width="545" alt="screen shot 2017-09-27 at 12 50 06 pm" src="https://user-images.githubusercontent.com/15836384/30928872-67c04308-a382-11e7-9c43-112a1be10d16.png">
<img width="242" alt="screen shot 2017-09-27 at 12 50 08 pm" src="https://user-images.githubusercontent.com/15836384/30928871-67c04ce0-a382-11e7-811f-a7038c370265.png">

**Comment by mikecreuzer** [comment]
Can put Kyler on Select menus, for now just do the other 2.
