### ISSUE TITLE
Cards and Match view: Banner default should be game logo, lastly BP logo

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#140]
If no game banner set, put game logo if we define it. If we do not, default back to BP logo.

<img width="733" alt="screen shot 2017-09-27 at 9 58 02 am" src="https://user-images.githubusercontent.com/1217271/30921142-5d364098-a36b-11e7-8e4a-6f8468cfa47e.png">

**Comment by Ian-Hitt** [comment]
requires: https://github.com/BattlePro/battlepro-issues/issues/122

**Comment by Ian-Hitt** [comment]
@mikecreuzer at the moment we are looping through tournaments, and using this to set the image
```<img src="@imagePath/battlepro/media/game-chooser/{$title.game_title_id}.jpg">```

Dont have a way to check if there is or is not an image until jake adds image upload field to game titles (as opposed to game franchises)

**Comment by mikecreuzer** [comment]
I feel like the loop should be the same, but nbd to do later.
