### ISSUE TITLE
Create new stage

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#153]
<img width="359" alt="screen shot 2017-11-21 at 11 36 41 am" src="https://user-images.githubusercontent.com/1217271/33087450-46ce2364-ceb0-11e7-9b29-318d4fdffa03.png">
<img width="355" alt="screen shot 2017-11-21 at 11 37 00 am" src="https://user-images.githubusercontent.com/1217271/33087466-50423cf0-ceb0-11e7-992f-376474180f94.png">

Note that you can choose 'conference'

**Comment by kylerc** [comment]
Going to make this as done.  The interface for this is working as expected now.  There are other issues for the missing functionality relating to stages / stage types.

**Comment by mikecreuzer** [comment]
Can I see UI? I havent seen it yet
