### ISSUE TITLE
'See All Games' button produces incomplete images

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#167]
When clicking the 'See All Games' button on the [Tournament Page](http://test.battlepro.com/tournaments/), it loads a pop up window with incomplete images producing a negative visual effect.

![capture](https://user-images.githubusercontent.com/6005869/35852323-47d0a740-0b33-11e8-861c-69f315b27b51.PNG)

**Comment by JakeBooher** [comment]
Currently, only featured games have an image. We'll just need to get images for all of the other games. Will assign to @Ian-Hitt and @nikkiradloff to get these taken care of

**Comment by JakeBooher** [comment]
Games without an image:

- [ ] Call of Duty: Ghosts
- [ ] Call of Duty: Black Ops III
- [ ] Call of Duty: Advanced Warfare
- [ ] Halo: Combat Evolved
- [ ] Halo 2
- [ ] Halo 3
- [ ] Halo Reach
- [ ] Halo 4
- [ ] Doom
- [ ] Gears of War 3
- [ ] Gears of War 4
- [ ] Hearthstone
- [ ] Heroes of the Storm

**Comment by nikkiradloff** [comment]
[bp-game-images-update.zip](https://github.com/BattlePro/battlepro-issues/files/1708137/bp-game-images-update.zip)

**Comment by Ian-Hitt** [comment]
added a fallback for no image
