### ISSUE TITLE
"See All Games" button confusion

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#169]
**Description:**
When viewing the [Tournaments ](http://test.battlepro.com/tournaments/) page and selecting a game, the mouse over effect displays message "_Game Title - See All Games_".  This can be very confusing when comparing to the "See All Games" button located very close to this area.

![seeallgames](https://user-images.githubusercontent.com/6005869/35853410-1300b656-0b36-11e8-8329-36d5101de3ac.PNG)

**Solutions**:
- Remove text "See All Games"
or
- Replace text with "View Events"

**Comment by JakeBooher** [comment]
I've just removed it entirely for now :)

**Comment by NikAlexander** [comment]
Issue still exists.  I've changed my request for this as well.  I would like the text to be changed to:

'view tournaments' 
or
'view matches'

This issue relates to:  https://github.com/BattlePro/battlepro-issues/issues/204
