### ISSUE TITLE
'FORUMS' text does not display when on FAQ page

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#172]
Description:
When visiting the [FAQ page](http://test.battlepro.com/support/faq#collapse2_3) and the user clicks on the 'FORUMS' tab there is no text on display, the icon is fully blue.

![forums](https://user-images.githubusercontent.com/6005869/35856381-84d742d8-0b3e-11e8-9908-f1925f5f427a.PNG)

**Comment by NikAlexander** [comment]
This issue also occurs while visiting the '[Teams Page](http://test.battlepro.com/teams/)' and clicking on the "Teams" tab.

![teams](https://user-images.githubusercontent.com/6005869/35857459-de2432f8-0b41-11e8-9319-d73ae5a07669.PNG)

**Comment by JakeBooher** [comment]
looks like this is specifically an issue with the hover text color on the active tab, so it'll happen on all of the tabs when they're active
