### ISSUE TITLE
Create 'Featured Leagues' Section on Leagues Listing Page

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#173]
Create a 'Featured Leagues' section on the leagues listing page.  Please create this as close as possible to the reference image provided below.

![leagueslisting](https://user-images.githubusercontent.com/6005869/35859536-20c2430a-0b49-11e8-870d-f60dabda8835.jpg)

**Comment by JakeBooher** [comment]
Will scope the view portion of this into #174, the data structure is available
