### ISSUE TITLE
"See All Articles" Button Produces Blank Page

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#175]
**Description:**
When user clicks the "See All Articles" button on the bottom of the articles page it directs the user to a blank page.

**All Articles Button:**
![capture](https://user-images.githubusercontent.com/6005869/35875224-40d8cdc0-0b77-11e8-8666-7fca81167ac4.PNG)

**Blank Page:**
![blank](https://user-images.githubusercontent.com/6005869/35875232-467c13c2-0b77-11e8-9d83-d39b73a4eac5.PNG)

**Comment by JakeBooher** [comment]
This was happening because there were no articles, the items displayed above that were features. I've just made one of the features into an article and it now displays on that empty page. However, it looks like the styling is a bit off so I'm going to create a new issue for that :)
