### ISSUE TITLE
'Manage Organizers' Page Enhancements

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#180]
I would like to make some overall enhancements to the 'Manage Organizers' page.  Changes include:

- [x] - Ability to transfer ownership of an organization to another organizer
- [x] - New visual presentation style for 'Owner' - removal of red star, new bold blue text color for owners
- [x] - Replace trash icon to 'X' for removing organizers
- [x] - Add new spacing for second row of organizers
- [] - Grant an organizer with Administrator privileges (has same abilities as owner except for disbandment and transfer of ownership)

Organizers Updated:
![organizers_updated](https://user-images.githubusercontent.com/6005869/35969393-5b53e474-0ccf-11e8-8f32-b9cdc829f117.jpg)

Organizers Original:
![organizers_original](https://user-images.githubusercontent.com/6005869/35969411-66b1fc98-0ccf-11e8-8f32-dcea3bfbb270.PNG)

**Comment by JakeBooher** [comment]
> New visual presentation style for 'Owner' - removal of red star, new bold blue text color for owners

We won't be able to change the user colors based on owner status as this functionality is reserved for user groups, so that may be confusing. I've added the "Owner" title below the username instead

> Grant an organizer with Administrator privileges (has same abilities as owner except for disbandment and transfer of ownership)

I'm not sure of a benefit of allowing anyone other than the owner of the league to transfer ownership or disband. In fact, it seems like it could be fairly dangerous, so I'll split this out into a separate issue for further discussion

**Comment by NikAlexander** [comment]
> We won't be able to change the user colors based on owner status as this functionality is reserved for user groups, so that may be confusing. I've added the "Owner" title below the username instead

Thats okay, we can just identify owners with this color in tournaments.  The colors will be different for staff in forums and I don't think the associations will cross over too much negatively.

Please go ahead and provide owners with the blue text color for the name.

> I'm not sure of a benefit of allowing anyone other than the owner of the league to transfer ownership or disband. In fact, it seems like it could be fairly dangerous, so I'll split this out into a separate issue for further discussion

Agreed, which is why in my original description of this issue I listed that 'Administrators' would have the same privelages as owners "except" for disbandment and transfer of ownership.  It seems that those comments were edited out when you created the checkbox visual layout.

**Comment by NikAlexander** [comment]
Please complete all of the enhancement items listed above.  

- Ability to select organizer and assign role as organizer, administrator, owner is not completed based on the original concept above.  please create the drop down arrow next to organizer usernames for selections.

- Owner of league username is not blue, please set the color to match the concept above, thanks

- Remove underline of each username for simplicity / enhancement

- Switch text colors of username and usergroup.  Username should be lighter than usergroup since it creates more contrast

- it is also too easy for an owner to transfer ownership.  This action should be asked to be performed for clarification / error compensation via popup window of some kind.  Its always good to verify these important actions more than once.

![transfer](https://user-images.githubusercontent.com/6005869/36399618-a42fd74c-159a-11e8-9f1e-68ffd254f99d.PNG)

**Comment by JakeBooher** [comment]
Unfortunately we really can't handle username styling separately in tournaments and they have to use the same function to generate the data and there isn't a way to extend this within XenForo

**Comment by mikecreuzer** [comment]
Since most all of this issue is done or hard to do with XenForo, closing it out. @NikAlexander if you really need anything specific, please recreate issue with specifics so that one can be kept open.
