### ISSUE TITLE
Ability for league administrators to be able to disband/transfer ownership

### ISSUE THREAD

**Issue by JakeBooher** [BattlePro/battlepro-issues#184]
From previous issue #180 
> Grant an organizer with Administrator privileges (has same abilities as owner except for disbandment and transfer of ownership)

**Comment by JakeBooher** [comment]
I'm not sure of a benefit of allowing anyone other than the owner of the league to transfer ownership or disband. In fact, it seems like it could be fairly dangerous, so I'll split this out into a separate issue for further discussion

**Comment by NikAlexander** [comment]
Agreed, that's why I wrote that administrators have the same privileges as owners "except" for disbandment and transfer of ownership.

**Comment by JakeBooher** [comment]
Ah yep, misread that. Have merged it back into #180
