### ISSUE TITLE
Tournament Game Landing Page Enhancements

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#190]
When on the tournaments page and selecting a game, the user is brought to a [landing page](http://test.battlepro.com/tournaments/halo-5) displaying all tournaments for this game.  Please make all visual / functional enhancements to this page so that it is near exact in comparison to the design concept provided below.

**New Design:**
![halotournamentslanding](https://user-images.githubusercontent.com/6005869/36262731-430f7998-1236-11e8-805a-6c04cb4a64c3.jpg)

**Existing Design:**
![tournament game landing original](https://user-images.githubusercontent.com/6005869/36262698-32e7ed16-1236-11e8-86e9-f43e21c3a682.PNG)

**Comment by NikAlexander** [comment]
**Background image for Halo 5**

![halo-5-guardians-skirmish-at-darkstar-concept-art-1](https://user-images.githubusercontent.com/6005869/36266011-85148f92-123e-11e8-8821-5e1b7aec88c2.jpg)

**Comment by mikecreuzer** [comment]
@Ian-Hitt this banner image should be opt in (for the header) - as in if we have an image. Otherwise leave it simple like we have now.

**Comment by Ian-Hitt** [comment]
@JakeBooher need to add open, past, and upcoming. re-assign to me when done

**Comment by JakeBooher** [comment]
`upcoming` exists, it's just the default. past also exists, it's just called `recent`

**Comment by JakeBooher** [comment]
`type=free`
`type=premium`
`type=featured`
`type=recent`
`type=open`
