### ISSUE TITLE
Enable Purchase Credit System

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#195]
Enable a credit system where users can purchase credits or redeem them for cash.  Users should have wallets to see how many credits they have stored in their account.  

- One credit should be equal to $1 USD

Options To Purchase in Wallet / Store:

- 5 coins / $5 USD
- 10 coins / $10 USD
- 25 coins / $15 USD
- 50 coins / $50 USD

![wallet](https://user-images.githubusercontent.com/6005869/36443108-d9494e08-1645-11e8-9d4f-ce19829c96b4.JPG)

**Comment by NikAlexander** [comment]
@mikecreuzer I know you guys developed your own credit system.  Do you think it will take care of everything we need?  I'm also looking at platforms used by our competition.  

BattleFy uses: https://www.xsolla.com/

**Comment by JakeBooher** [comment]
Our credit system is already implemented: https://www.battlepro.com/credits/packages
