### ISSUE TITLE
Submitting New League Doesn't Display for User

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#196]
When a user is creating a new league and 'submits' it, it will not be visible / retrievable if all of the subsequent info is not filled out.  The league will save to a users profile which can be seen through the image below:

![nik s test league](https://user-images.githubusercontent.com/6005869/36291041-b5c88ec4-1296-11e8-9c72-1bcc53ee5a73.PNG)

Even though these leagues have been initiated / saved, I am not able to modify the content or know how to pull it up again.  Perhaps the language on the first step is misleading.  We should change it from 'submit' to 'save and continue'.  

**Remove this page entirely since the information is asked a second time immediately after the user provides this information:**
![remove page](https://user-images.githubusercontent.com/6005869/36456745-668d326a-1674-11e8-9ef9-4d6a487bf586.JPG)

**Start 'CREATE LEAGUE' process with this page instead:**
If we start on this page, it will be the same process as creating a tournament.  Where after submitting the first page, the league is created and then the subsequent sections to 'manage league'.  This gets rid of the first page when creating a league which is not needed since its the same here.
![create league](https://user-images.githubusercontent.com/6005869/36456753-73186bb2-1674-11e8-87fd-6d8a5c90753d.JPG)

**Comment by JakeBooher** [comment]
@NikAlexander the issue is that we can't provide the tabbed interface with all of the additional details until the record is created, and the requirements for that initial record are the title and about section so unfortunately we can't really get rid of that page. I have made it redirect to the "Branding" tab instead to be a simpler process
