### ISSUE TITLE
ForgeHub API Pulling Maps From Incorrect Game

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#199]
When creating a tournament for Halo 5 and selecting maps from ForgeHub the maps listed are not from the game Halo 5.  The maps provided are from the game: 'Halo 2: Anniversary (Master Chief Collection).

**Image from test site:** Notice the UI is broken here as well
![halo 2a maps](https://user-images.githubusercontent.com/6005869/36343299-634f3e20-13d8-11e8-87f1-0e8eee7878bb.PNG)

**Image from Live Site:** (this actually pulls maps from Halo 5 correctly)
![tri](https://user-images.githubusercontent.com/6005869/36353549-c163cc66-1495-11e8-99f3-316d86090c4d.PNG)

**Comment by kylerc** [comment]
@JakeBooher can you look into sorting out the ID portion of this?

**Comment by kylerc** [comment]
I believe my part of this is resolved in my next push.

**Comment by NikAlexander** [comment]
Relates to issue: https://github.com/BattlePro/battlepro-issues/issues/254

**Comment by JakeBooher** [comment]
@kylerc what ID issue are you referring to exactly?

**Comment by kylerc** [comment]
@JakeBooher It seems like the wrong game id is being used to search the forgehub api based on Nik's comment above.  Haven't personally verified this though.

**Comment by JakeBooher** [comment]
The IDs don't really line up directly, the ForgeHub IDs are:								
```
1: Halo 2
2: Halo 3
3: Halo Reach
4: Halo 4
5: Halo 5
```

and BattlePro IDs are:

```
9: Halo 2
11: Halo 3
16: Halo Reach
3: Halo 4
1: Halo 5
```

I think currently the best option would be to set these IDs in conditionals within the templates would be the path of least resistance, at least for MVP:

```
<xen:if is="{$gameTitle.game_title_id} === 9">
<xen:set var="$fhGameId" value="1" />
</xen:if>
<xen:if is="{$gameTitle.game_title_id} === 11">
<xen:set var="$fhGameId" value="2" />
</xen:if>
<xen:if is="{$gameTitle.game_title_id} === 16">
<xen:set var="$fhGameId" value="3" />
</xen:if>
<xen:if is="{$gameTitle.game_title_id} === 3">
<xen:set var="$fhGameId" value="4" />
</xen:if>
<xen:if is="{$gameTitle.game_title_id} === 1">
<xen:set var="$fhGameId" value="5" />
</xen:if>
```

Not really sure where you're pulling the IDs from currently

**Comment by kylerc** [comment]
@JakeBooher I think this just needs to correctly set in the `bpro_tournament_mapInput` template.  The JS is getting global variables from that templates and using them for the API call.  Can you add that in?

**Comment by NikAlexander** [comment]
Reopening, this is a critical bug that is preventing me from hosting a tournament today.  The map picker is still only showing games from Halo Master Chief Collection when typing in map names for a Halo 5 tournament.  

- Need to create a way to enter in custom map information for the occasion that a map is not in ForgeHub's library / accessible.

![select map](https://user-images.githubusercontent.com/6005869/37239797-79b8bf0a-240f-11e8-8693-a1fa83be717d.JPG)

![narrows](https://user-images.githubusercontent.com/6005869/37239798-7d94c6fa-240f-11e8-88b0-35b26e3410ac.JPG)

**Comment by JakeBooher** [comment]
@NikAlexander got this sorted out and pushed the template changes to the live site

**Comment by NikAlexander** [comment]
Thanks for pushing this out to the live site :)
