### ISSUE TITLE
Create Tournament 'Results' Page

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#201]
When a tournament has been completed the user is still viewing the tournament listing in the same format it was first posted.  The concluded tournament has some interesting information to share and we should do a better job of visually presenting that to the user.  Please create this experience based on the concept below as close as possible:

![results overview](https://user-images.githubusercontent.com/6005869/36346636-1e5b6ac2-1410-11e8-9169-13a4f6969a99.PNG)

![standings](https://user-images.githubusercontent.com/6005869/36346637-20798668-1410-11e8-9a81-505ae7d44eac.PNG)

Our Current Results Page:
![tournament](https://user-images.githubusercontent.com/6005869/36346600-32971780-140f-11e8-8a0a-041b24785509.PNG)

![bracket](https://user-images.githubusercontent.com/6005869/36346734-feba873c-1411-11e8-8e5a-d3050f2aec20.PNG)

**Comment by Ian-Hitt** [comment]
@NikAlexander there is already a results page, it just does not show up until the tournament has been completed.

**Comment by Ian-Hitt** [comment]
@kylerc lmk when I can re-test this to see what needs to be updated.

**Comment by kylerc** [comment]
@Ian-Hitt this should now be possible for single stage elimination tournaments.  That should be enough to generate the info you need though.
