### ISSUE TITLE
Clicking 'Manage Team' Produces Server Error

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#202]
When logged in and attempting to 'manage' a team that belongs to a league, the user is brought to a server error page.

**Repro**:
- Login to account 'new york titans' with password: '***'
- View team page for '[New York Titans](http://test.battlepro.com/teams/new-york-titans.18/view)'
- Click on 'manage team'
- Observer server error notification

Server Error Notification:
![server error](https://user-images.githubusercontent.com/6005869/36348629-14da031e-1442-11e8-9102-1615a74ee0ad.PNG)

**Comment by JakeBooher** [comment]
@NikAlexander just a reminder that the issues repository is public so it's probably best not to include passwords. Looking into this issue now

**Comment by JakeBooher** [comment]
It looks like one of the recent changes we've made has resolved this issue
