### ISSUE TITLE
Change 'Tournaments' Image Icon

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#208]
Change the image icon for tournaments on the main nav bar from calendar to trophy.  Leagues will have a different image icon associated with it.

![tournaments](https://user-images.githubusercontent.com/6005869/36403052-7d1814d8-15b0-11e8-9ef6-888b960d69ce.PNG)

**Comment by mikecreuzer** [comment]
@Ian-Hitt talked with Nik lets keep material (we may want to try MDI? idk if thatll work)

**Comment by NikAlexander** [comment]
Not sure what decision was made on this and just want to clarify a bit.  Would like the trophy logo to be associated with 'tournaments' tab.  

**Note:**
The image icon for leagues should be changed to the shield image icon.

**Comment by Ian-Hitt** [comment]
@NikAlexander yes, this is how it is.
