### ISSUE TITLE
Main Nav Bar Enhancements

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#210]
Please change the order of the tabs in the main nav bar so that they are prioritized in order of importance listed below:

- News
- Forums
- Tournaments
- Matches
- Teams
- Leagues

- [x] Prioritize order of tabs

- [ ] Change color of selected tab from blue to white (keep blue underline as is)

- [ ] Change color of mouse over effect from white to blue 

![navbar](https://user-images.githubusercontent.com/6005869/36426565-5d55102a-1618-11e8-9035-1b45b051849a.jpg)

**Comment by Ian-Hitt** [comment]
@JakeBooher needs re-ordered in the add-on
