### ISSUE TITLE
League Page Enhancements

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#214]
The current League page is in need of some visual enhancements. Create a new visual layout based on the image provided below.

New Theme:
![leaguepage2](https://user-images.githubusercontent.com/6005869/36931635-55da2eca-1e88-11e8-99e0-0ff2b30b7eae.jpg)

Original Theme:
![original](https://user-images.githubusercontent.com/6005869/36433274-18c7a186-162a-11e8-9b66-5fbfe7a0dbc6.JPG)

**Comment by mikecreuzer** [comment]
I assume this page should also show on the events the teams/people battling. Moving this also to a later date since we cannot make this by next week.

**Comment by NikAlexander** [comment]
@mikecreuzer  Not quite sure if I understand how teams would be shown battling on this page.  I think the brackets would be visible to users once they click on an event in the 'events' tab.  That would then open up the tournament page where 'brackets' would have its own tab for viewing.
