### ISSUE TITLE
Nav Bar Enhancement for Leagues

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#215]
When a user has created at least one league or signed up to at least one league then the names of these leagues will appear in the drop down main nav menu as shown below:

**Note**:

- Please do the same for 'Teams'.  When a player creates or joins a team then the name of that team will be in the drop down under 'leaderboards'.

- Please do the same for 'Tournaments'.  When a user creates or joins a tournament and it is NOT complete then the name of the tournament will show up below where it says 'tournaments'.  When a tournament has concluded then the name of this tournament will be removed 12 hours after the expiration date.

![leagues nav](https://user-images.githubusercontent.com/6005869/36435008-6cb44bf6-162e-11e8-8423-a2282677700c.jpg)

**Comment by Ian-Hitt** [comment]
@JakeBooher needs this data globally. Re-assign to me if you'd like me to add them in once your done.
