### ISSUE TITLE
Main Navigation Enhancement

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#224]
When a user is on a specific drop down selection from the main navigation sidebar, there is no indication which section the user is in.  For clarity please change the color of the currently visited sub section white.

**Example**:
- When a user is visiting the 'Leaderboards' page, the 'leaderboards' text in the sidebar will be white.
![whitetextr](https://user-images.githubusercontent.com/6005869/36520821-69a8ea8c-1761-11e8-93d2-c6560175092d.JPG)

**Comment by Ian-Hitt** [comment]
XenForo does not have support for active navigation for sub navigation items, only the parent navigation items.
