### ISSUE TITLE
Make Animation on Homepage Bigger

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#227]
The tournament bracket and cup animation on the homepage is very small.  Would like to make more visual impact here.  Make it much larger so its easier to see and more exciting.

![bigger](https://user-images.githubusercontent.com/6005869/36606726-987fc33a-1892-11e8-8f3f-dc71b0ea02b3.jpg)

**Comment by mikecreuzer** [comment]
Also fixed on our version
