### ISSUE TITLE
Change Tournaments to use first stage for number of players

### ISSUE THREAD

**Issue by kylerc** [BattlePro/battlepro-issues#232]
Currently is using the info from the game info page.

**Comment by JakeBooher** [comment]
I've looked into this and there is quite a bit using this value. Could we make the first stage inherit from the tournament value instead?

**Comment by kylerc** [comment]
@JakeBooher might be easier to just have the saving of stages get this value and apply it to the tournament itself?  Could we do the same thing to the start time for the tournament?

**Comment by JakeBooher** [comment]
@kylerc just realized something, are we talking about number of players or number of teams? I'm not sure how number of players per team is relevant to stages and this value is used for several other things before the stage page is accessed. Number of teams on the other hand shouldn't be a major change

**Comment by kylerc** [comment]
Sorry, correct number of teams not number of players.  You should also be able to get the start time and date from the first stage and apply those.

**Comment by JakeBooher** [comment]
Alright, that won't be an issue then 👍
