### ISSUE TITLE
Joining a tournament as a PBL team not working?

### ISSUE THREAD

**Issue by kylerc** [BattlePro/battlepro-issues#234]
Gives the error `The team name you have chosen is already in use.`.  Was trying to join a tournament when logged in as the user.

**Comment by JakeBooher** [comment]
What user were you logged in as, and is the tournament a solo or team tournament?

**Comment by kylerc** [comment]
Logged in as St Louis Sentinels and Atlanta Zenith.  Both had the same issue.  Was a solo tournament (ID 3 on test server).  Other accounts seem to be able to join correctly.

**Comment by JakeBooher** [comment]
Probably be an issue with a user name matching an existing team name rather than being related to leagues
