### ISSUE TITLE
New conversation: modal sticky left

### ISSUE THREAD

**Issue by nikkiradloff** [BattlePro/battlepro-issues#241]
<img width="1381" alt="screen shot 2018-03-01 at 11 01 39 am" src="https://user-images.githubusercontent.com/15836402/36858125-ef473b74-1d3f-11e8-8c02-e87a57724e88.png">

**Comment by Ian-Hitt** [comment]
Cant replicate

**Comment by kylerc** [comment]
@mikecreuzer I'm still unable to replicate this on my machine but it apparently happens on Nikki's computer.  You seemed like you were familiar with this issue somewhat, any ideas for reproducing it?
