### ISSUE TITLE
Saving previous information in a tournament clears staging

### ISSUE THREAD

**Issue by kylerc** [BattlePro/battlepro-issues#244]
Should only clear staging if staging is saved but can leave it if previous steps are saved.

**Comment by JakeBooher** [comment]
What "previous information" are you referring to?

**Comment by kylerc** [comment]
Saving the steps before staging.  Basic info, game info, or the tournament info

**Comment by JakeBooher** [comment]
This is only supposed to reset if `max_teams` is changed, I've disabled this for now
