### ISSUE TITLE
Create match: super smash has halo title (Live site only)

### ISSUE THREAD

**Issue by nikkiradloff** [BattlePro/battlepro-issues#249]
in that case, halo is missing halo 2 title
<img width="863" alt="screen shot 2018-03-01 at 12 19 58 pm" src="https://user-images.githubusercontent.com/15836402/36861920-f8d1845a-1d4a-11e8-9575-c5452704a2bb.png">

**Comment by JakeBooher** [comment]
This was fixed in the installer, will be addressed automatically when we push the changes
