### ISSUE TITLE
Game logos are missing from tournament/match cards

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#252]
<img width="607" alt="screen shot 2018-03-01 at 2 38 16 pm" src="https://user-images.githubusercontent.com/1217271/36868524-346ed702-1d5e-11e8-9708-0057751f9473.png">

**Comment by Ian-Hitt** [comment]
@JakeBooher this is being dumped from database, not sure exactly how it set up.

**Comment by JakeBooher** [comment]
What page are you on? They show up for me

<img width="1247" alt="screen shot 2018-03-01 at 2 54 45 pm" src="https://user-images.githubusercontent.com/179180/36869202-8e354aee-1d60-11e8-9880-a889694394b3.png">

**Comment by mikecreuzer** [comment]
@JakeBooher tournaments
