### ISSUE TITLE
Selected maps looks broken

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#254]
Under manage tournament

<img width="1228" alt="screen shot 2018-03-01 at 2 40 42 pm" src="https://user-images.githubusercontent.com/1217271/36868637-920315a4-1d5e-11e8-91a6-751b9cc901aa.png">

**Comment by NikAlexander** [comment]
Relates to issue: https://github.com/BattlePro/battlepro-issues/issues/199

**Comment by kylerc** [comment]
@mikecreuzer was this on the test server or the development environment?

**Comment by mikecreuzer** [comment]
Sorry @NikAlexander duplicate, @kylerc can talk there but development, stages branch
