### ISSUE TITLE
Setup Bpro paypal

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#255]
All Ill need when done is email, then purchasing credits will work, apparently that wasnt done.

**Comment by mikecreuzer** [comment]
@NikAlexander any luck on this? We will get an error when people try to buy something (since there is no paypal setup)

**Comment by NikAlexander** [comment]
![image](https://user-images.githubusercontent.com/6005869/37166862-3c9c49f8-22ce-11e8-94d6-8a4f939eab32.png)
![image](https://user-images.githubusercontent.com/6005869/37166900-536196ca-22ce-11e8-9c5f-c8c5e71e7b3c.png)

**Comment by mikecreuzer** [comment]
@JakeBooher do we need login details or anything?
