### ISSUE TITLE
Subtle homepage improvements

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#258]
- [x] unround pill style tabs (we dont use pill style anywhere else so we shouldnt start here)
- [x] Remove blue pill style from time on card
- [x] Logos missing on featured items, card is blank
- [x] Remove gradient on active state on featured tournaments (way too obnoxious) 

<img width="608" alt="screen shot 2018-03-02 at 3 55 40 pm" src="https://user-images.githubusercontent.com/1217271/36923914-5f5a6164-1e32-11e8-9839-6e7160ed3a95.png">
<img width="1393" alt="screen shot 2018-03-02 at 3 56 38 pm" src="https://user-images.githubusercontent.com/1217271/36923921-615239ec-1e32-11e8-8661-e3d4edeba270.png">

**Comment by Ian-Hitt** [comment]
@JakeBooher game logo isnt available on index
