### ISSUE TITLE
Navigation SideBar Styling 

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#259]
After viewing some recent changes to the navigation bar, I felt that they were visually loud and would want to take a more subtle approach.  

- [x] Remove green / blue background color

- [x] Remove mouse over animation where the darkness goes from left to right 

- [x] Make image icons same color as text 

Overall I'm in favor of the styling of the image below.  Please make visual enhancements to match this concept. (please note: a separate issue exists that addresses the image icons assocaited with each tab)
![mainnav](https://user-images.githubusercontent.com/6005869/36928052-13479d64-1e50-11e8-9f33-ba6f14203533.jpg)

New Styling:
![nav bar style](https://user-images.githubusercontent.com/6005869/36928058-28bb5d84-1e50-11e8-9d2d-81c1ba420c70.JPG)

![unnamed](https://user-images.githubusercontent.com/6005869/36928060-2c5b3040-1e50-11e8-9fc0-ae17e969b2e3.png)

**Comment by NikAlexander** [comment]
Styling changes still visible on live site.  Reopening.

Can we also revert the style of this to be an underline instead of the left side column?  Please make sure to use the blue color and not the green for this as well.
![navbar](https://user-images.githubusercontent.com/6005869/37170210-39371c5c-22d8-11e8-93ec-86b344364a49.JPG)

**Comment by Ian-Hitt** [comment]
<img width="411" alt="screen shot 2018-03-12 at 2 35 44 pm" src="https://user-images.githubusercontent.com/15836384/37305504-ab364616-2602-11e8-976e-3bb0658ab8e6.png">

**Comment by Ian-Hitt** [comment]
Will push to live in next update
