### ISSUE TITLE
Tournament Start Time Display Style 

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#261]
Regarding the text display style for tournament start times, would prefer to keep it more simple.  I like the accurateness of displaying tournaments starting in say "17 Hours" but not "6 days and 4 Hours" (as an example).

Here are ways I think we can simplify. 

- For tournaments starting less than 1 day, display hours
- For tournaments starting in 1 day or more, only display the number of days (ie. "IN 2 DAYS")
- If a tournament is closed for registration because it is currently in progress, do not display past time such as "4 hours 56 Mins Ago".  Instead, just display the text "LIVE" to show that the tournament is in progress / currently active.  If the event has concluded and no further participation is required by the players then display nothing in this space.

![tournament start time](https://user-images.githubusercontent.com/6005869/36928582-055d8ba0-1e55-11e8-915c-860790d778c6.jpg)

**Comment by Ian-Hitt** [comment]
Fixed phrases on live site, live portion fixed on dev theme.
