### ISSUE TITLE
Tournament Card Enhancements

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#264]
I noticed a few things that could enhance the tournament cards.  By reviewing the concept I created to the one currently built, I noticed a few key differences.

- [x] Tournament name and prizing dollar ammount ($0) should be bold and the same font size

- [x] Tournament host name should replace where it says 'Team' or 'Solo'

- [x] Prizing should be capitalized to 'PRIZING' so that it matches formatting of the game title.

- [x] if region is 'N/A' then write 'North America' because some may be confused with 'non applicable' denomination

- [x] Font size of tournament name could be slightly larger

![tournament cards](https://user-images.githubusercontent.com/6005869/36938718-b15b338c-1ef3-11e8-8088-e77526aac645.JPG)

**Comment by Ian-Hitt** [comment]
@NikAlexander that actually is "not applicable." North America states "North America."
