### ISSUE TITLE
Parallax incorrectly applying to hero mask

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#276]
<img width="377" alt="screen shot 2018-03-05 at 10 35 13 am" src="https://user-images.githubusercontent.com/1217271/36987030-027b7dda-2061-11e8-8155-0640dc68f985.png">

**Comment by Ian-Hitt** [comment]
@mikecreuzer steps to replicate? im not getting this error

**Comment by mikecreuzer** [comment]
I just posted this minutes ago, and now the mask is just gone for me: http://10.1.10.83/battlepro/index.php?threads/heres-a-halo-thread.14/#post-22

Something goofy.

**Comment by mikecreuzer** [comment]
The mask seems to disappear with inspector open
