### ISSUE TITLE
Profile page sticky sidebar/clearfix bug

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#277]
<img width="1232" alt="screen shot 2018-03-05 at 10 43 51 am" src="https://user-images.githubusercontent.com/1217271/36987509-2732830c-2062-11e8-9838-fa5a6b71e134.png">

- [x] Sticky sidebar from top incorrect
- [x] Sidebar itself causes clearfix (see teams tab)

http://10.1.10.83/battlepro/index.php?members/audentio.2/

**Comment by Ian-Hitt** [comment]
@mikecreuzer not sure what is meant by "Sticky sidebar from top incorrect" but everything appears to be in order for me.

**Comment by Ian-Hitt** [comment]
sidebar sticky not accounting for side navigation
