### ISSUE TITLE
Editors no longer showing up on manage tournament

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#278]
http://10.1.10.83/battlepro/index.php?tournaments/test-tournament.9/manage-details
<img width="914" alt="screen shot 2018-03-05 at 10 50 25 am" src="https://user-images.githubusercontent.com/1217271/36987904-12a2e08e-2063-11e8-93e6-680999e4e937.png">

**Comment by JakeBooher** [comment]
I'm not able to replicate this. Make sure you're in the correct branch/style otherwise this would be something Ian would need to have a look into

**Comment by Ian-Hitt** [comment]
not able to replicate either
