### ISSUE TITLE
Support search broke

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#28]
<img width="418" alt="screen shot 2017-08-07 at 6 50 18 pm" src="https://user-images.githubusercontent.com/1217271/29050395-4daa1cb8-7ba1-11e7-9137-c8abef48d2b0.png">

**Comment by Ian-Hitt** [comment]
https://www.test.battlepro.com/admin.php?templates/bp_support_faq.826/edit&style_id=6
