### ISSUE TITLE
Live: can't select username when trying to add team members

### ISSUE THREAD

**Issue by nikkiradloff** [BattlePro/battlepro-issues#288]
Get a flash of the username but not able to select as I type
<img width="439" alt="screen shot 2018-03-05 at 11 30 24 am" src="https://user-images.githubusercontent.com/15836402/36989889-a2e27d26-2068-11e8-973c-b8229dae46e3.png">

**Comment by kylerc** [comment]
@nikkiradloff fixed on dev :).

**Comment by NikAlexander** [comment]
Yes, I was looking at this as well.  https://github.com/BattlePro/battlepro-issues/issues/178
