### ISSUE TITLE
What are the social media links?

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#29]
I need these for footer.

**Comment by NikAlexander** [comment]
unfortunately, we don't have social media accounts set up for battlepro.  Once I receive the final trademark approved though the trademark bureau then I can apply to reclaim the inactive twitter account: @battlepro.

I did however reserve a youtube page. Will update you on that soon.

**Comment by NikAlexander** [comment]
Instagram: https://www.instagram.com/battle_pro/

YouTube: 

Twitter: N/A - will need to wait for final trademark approval to complete so I can reclaim inactive twitter account: @battlepro.

**Comment by mikecreuzer** [comment]
@NikAlexander any update on this one?
