### ISSUE TITLE
When searching for teams, no username shows as a I type

### ISSUE THREAD

**Issue by nikkiradloff** [BattlePro/battlepro-issues#298]
<img width="466" alt="screen shot 2018-03-06 at 3 54 34 pm" src="https://user-images.githubusercontent.com/15836402/37060710-b778bbf8-2156-11e8-9029-f6b14f015526.png">

**Comment by kylerc** [comment]
@nikkiradloff this is on the live style right?  On the `/index.php?teams/(team id)/manage-members` route?  From what I can tell on live this is working for me currently, but maybe there's something else going on.

**Comment by nikkiradloff** [comment]
Yeah on live. I was creating a league at the time and nothing popped up for me at least

**Comment by kylerc** [comment]
Ah yep I can replicate that.  @JakeBooher can you take this?  Looks like just needs template setup as an autocomplete to whatever the backend is using for this.

**Comment by JakeBooher** [comment]
I don't think we have an autofill JS function for teams, XenForo's auto complete isn't something you can use for other content types, so we'll probably need that as well

**Comment by JakeBooher** [comment]
Actually -- looks like we have an endpoint already: `teams/find?q=inputvalue` so this is strictly a JS thing currently it appears

**Comment by JakeBooher** [comment]
Tracked down js/battlepro/tournament/teamAutoComplete.js, so it appears this exists already -- will get it hooked up
