### ISSUE TITLE
/tournaments: missing game think Halo: Combat Evolved

### ISSUE THREAD

**Issue by nikkiradloff** [BattlePro/battlepro-issues#306]
<img width="731" alt="screen shot 2018-03-06 at 4 50 37 pm" src="https://user-images.githubusercontent.com/15836402/37063339-b3bcce5c-215e-11e8-9500-b04bd8c75d19.png">

**Comment by Ian-Hitt** [comment]
game exists on dev, as does image. may just not be in DB for live site?

**Comment by JakeBooher** [comment]
This was intentional, there was an issue to remove it a while ago, the upgrade script just reset the values to empty instead of removing it
