### ISSUE TITLE
Joining tournament: getting errors when selecting the correct amount of players

### ISSUE THREAD

**Issue by nikkiradloff** [BattlePro/battlepro-issues#311]
![tournament-join](https://user-images.githubusercontent.com/15836402/37103087-0adfe51c-21ef-11e8-8ee1-3d664b72247b.gif)

**Comment by JakeBooher** [comment]
Looks like this is ultimately down to having the checkbox selected for "Require entry fee" but not actually setting the fee. I'll have that block publishing
