### ISSUE TITLE
Parse out BB code in News snippets

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#312]
Also the fact that these dont have at least a 100 chars is probably problematic. People go to the news page and will want at least a little bit to read before clicking.

**Comment by Ian-Hitt** [comment]
@mikecreuzer Nik seems to adamantly want this EXACT design https://github.com/BattlePro/battlepro-issues/issues/192

I'll do the bbcode snippets though

**Comment by Ian-Hitt** [comment]
@mikecreuzer thats not bbcode, that XF placeholder for image, xen:helper snippet ignores it because its just text.
