### ISSUE TITLE
Creating tournament: need region/language input

### ISSUE THREAD

**Issue by nikkiradloff** [BattlePro/battlepro-issues#315]
![screen shot 2018-03-07 at 11 08 45 am](https://user-images.githubusercontent.com/15836402/37106653-fcb25200-21f7-11e8-87c9-508be2a1f183.png)

**Comment by kylerc** [comment]
@JakeBooher can you take care of adding these fields and saving them?  I've still got a fair bit to get through today.

**Comment by JakeBooher** [comment]
The region input exists for the games that have regions, Rocket League doesn't have them, it appears, so probably just need to have @Ian-Hitt not display the value if it isn't set

**Comment by Ian-Hitt** [comment]
that is Not applicable...
