### ISSUE TITLE
I think this should say players not teams, since I create a solo tournament style

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#32]
<img width="886" alt="screen shot 2017-08-08 at 10 54 37 am" src="https://user-images.githubusercontent.com/1217271/29081372-05547968-7c28-11e7-9277-bd98157e1c3c.png">

Not sure if this is just a string thing.

**Comment by NikAlexander** [comment]
correct, would be better suited if these were called 'Min Players' and 'Max Players'.
