### ISSUE TITLE
Create tournament: saved stage time as 6pm, after save says 20pm

### ISSUE THREAD

**Issue by nikkiradloff** [BattlePro/battlepro-issues#325]
<img width="447" alt="screen shot 2018-03-07 at 2 52 41 pm" src="https://user-images.githubusercontent.com/15836402/37117593-501aff68-2217-11e8-8244-786ef0d11c65.png">

**Comment by kylerc** [comment]
Issue is if the account's timezone doesn't match I think.  For demo can we set the account to be CST @JakeBooher ?

**Comment by JakeBooher** [comment]
Yeah, that should be fine. @nikkiradloff can you set the timezones for demo users to CST? Right the backend  is assuming everything is entered using the user's timezone set in XenForo
