### ISSUE TITLE
Tournament: unable to report the score of last match as tournament starter

### ISSUE THREAD

**Issue by nikkiradloff** [BattlePro/battlepro-issues#328]
<img width="991" alt="screen shot 2018-03-07 at 3 29 43 pm" src="https://user-images.githubusercontent.com/15836402/37119444-09246d50-221d-11e8-9a20-098782907ab8.png">

**Comment by kylerc** [comment]
@nikkiradloff can you link me to this tournament?

**Comment by kylerc** [comment]
Oh actually, I found it.  I believe this will be fixed once we push the dev changes to live.
