### ISSUE TITLE
Wager should show currency

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#329]
<img width="379" alt="screen shot 2018-03-07 at 3 35 12 pm" src="https://user-images.githubusercontent.com/1217271/37119517-3eae0a44-221d-11e8-9277-616ac59dcea3.png">

For now just put USD $ sign.

**Comment by Ian-Hitt** [comment]
@mikecreuzer Nik made us change is specifically

**Comment by Ian-Hitt** [comment]
He wants it to say Free if wager == 0

**Comment by Ian-Hitt** [comment]
Unless you mean something else?

**Comment by mikecreuzer** [comment]
Im referring to creating a tournament that has a wager. Wager without a unit doesn't mean anything. Just put `Wager (in $ USD)` or something for now as the field name

**Comment by mikecreuzer** [comment]
Or prefix input with a $

**Comment by Ian-Hitt** [comment]
yeah okay, they already do that
