### ISSUE TITLE
Standardize gametype and maps per game

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#33]
If we have a game selected we should be able to compile native gametypes and maps.

Custom maps/gametypes should be an option as well.

**Comment by JakeBooher** [comment]
@NikAlexander can you get me a list of the most common competitive maps for each of the games?

**Comment by NikAlexander** [comment]
Here is a list of games and modes for Halo 5: Guardians competitive settings.  It would be great if you could create a way for BattlePro staff to enter in these details manually on the site somewhere.  That way we don't need to resort to the xenforo admin panel to update maps or modes, we can do it straight from the site itself. 

**Halo 5 Competitive settings:**
**Maps**: 
https://www.halowaypoint.com/en-us/games/halo-5-guardians/xbox-one/map-variants?lastModifiedFilter=Everything&sortOrder=BookmarkCount&page=1&gamertag=Official%20HCS
**Team Maps:**
	- [Regret](https://www.halowaypoint.com/en-us/games/halo-5-guardians/xbox-one/map-variants?lastModifiedFilter=Everything&sortOrder=BookmarkCount&page=1&gamertag=Official%20HCS#ugc_halo-5-guardians_xbox-one_mapvariant_Official%20HCS_16758b32-ea28-4070-ae3c-e7fe8447dff7)
	- [The Rig](https://www.halowaypoint.com/en-us/games/halo-5-guardians/xbox-one/map-variants?lastModifiedFilter=Everything&sortOrder=BookmarkCount&page=1&gamertag=Official%20HCS#ugc_halo-5-guardians_xbox-one_mapvariant_Official%20HCS_5baeead5-090e-4cce-9f78-fb8da832338f)
	- [Plaza](https://www.halowaypoint.com/en-us/games/halo-5-guardians/xbox-one/map-variants?lastModifiedFilter=Everything&sortOrder=BookmarkCount&page=1&gamertag=Official%20HCS#ugc_halo-5-guardians_xbox-one_mapvariant_Official%20HCS_d465ea63-50f8-43f5-a7f0-40c0999b3901)
	- [Fathom](https://www.halowaypoint.com/en-us/games/halo-5-guardians/xbox-one/map-variants?lastModifiedFilter=Everything&sortOrder=BookmarkCount&page=1&gamertag=Official%20HCS#ugc_halo-5-guardians_xbox-one_mapvariant_Official%20HCS_9a4e2c4b-08ea-4135-9d51-07c643325e43)
	- [Truth](https://www.halowaypoint.com/en-us/games/halo-5-guardians/xbox-one/map-variants?lastModifiedFilter=Everything&sortOrder=BookmarkCount&page=1&gamertag=Official%20HCS#ugc_halo-5-guardians_xbox-one_mapvariant_Official%20HCS_623abed7-2098-45c8-bb92-fbe58c8b46e5)
	- [Coliseum](https://www.halowaypoint.com/en-us/games/halo-5-guardians/xbox-one/map-variants?lastModifiedFilter=Everything&sortOrder=BookmarkCount&page=1&gamertag=Official%20HCS#ugc_halo-5-guardians_xbox-one_mapvariant_Official%20HCS_3d755478-35e6-4e85-b216-1a8c43099f45)
	- [Eden](https://www.halowaypoint.com/en-us/games/halo-5-guardians/xbox-one/map-variants?lastModifiedFilter=Everything&sortOrder=BookmarkCount&page=1&gamertag=Official%20HCS#ugc_halo-5-guardians_xbox-one_mapvariant_Official%20HCS_8fbf6f97-6869-43ea-a306-44de3b3ac61f)
	- [Empire](https://www.halowaypoint.com/en-us/games/halo-5-guardians/xbox-one/map-variants?lastModifiedFilter=Everything&sortOrder=BookmarkCount&page=1&gamertag=Official%20HCS#ugc_halo-5-guardians_xbox-one_mapvariant_Official%20HCS_cf6fea30-afb4-479a-9b41-0021d00ac6ad)

**Solo Maps (FFA):**
Truth FFA HCS
Regret FFA HCS
Mercy FFA HCS

**Modes:**
https://www.halowaypoint.com/en-us/games/halo-5-guardians/xbox-one/game-variants?lastModifiedFilter=Everything&sortOrder=BookmarkCount&page=1&gamertag=Official%20HCS
	- HCS FFA Slayer
(Solo Mode Only)
	https://www.halowaypoint.com/en-us/games/halo-5-guardians/xbox-one/game-variants?lastModifiedFilter=Everything&sortOrder=BookmarkCount&page=1&gamertag=Official%20HCS#ugc_halo-5-guardians_xbox-one_gamevariant_Official%20HCS_07ad4139-b774-4c07-826c-3befcd244480
	- Slayer HaloWC
	https://www.halowaypoint.com/en-us/games/halo-5-guardians/xbox-one/game-variants?lastModifiedFilter=Everything&sortOrder=BookmarkCount&page=1&gamertag=Official%20HCS#ugc_halo-5-guardians_xbox-one_gamevariant_Official%20HCS_7462a236-9d97-43ae-9743-284257e11b4e
	- Capture the Flag HaloWC
	https://www.halowaypoint.com/en-us/games/halo-5-guardians/xbox-one/game-variants?lastModifiedFilter=Everything&sortOrder=BookmarkCount&page=1&gamertag=Official%20HCS#ugc_halo-5-guardians_xbox-one_gamevariant_Official%20HCS_21449261-47e3-4741-81d4-616d95f426d5

**Comment by mikecreuzer** [comment]
@NikAlexander we cannot do form management in this system, it was setup without that in mind. Can you get us a list of each game and each field? Jake made players per team match up with game and added default maps, but if we rebuild the system this would be something we could scope in.
