### ISSUE TITLE
Add stream button doesn't seem to function

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#331]
<img width="1327" alt="screen shot 2018-03-07 at 3 40 08 pm" src="https://user-images.githubusercontent.com/1217271/37119707-d9d4ff0a-221d-11e8-98db-056c696e5cc8.png">

**Comment by mikecreuzer** [comment]
Clcking it doesn't add a row like it did before. Lowish priority.

**Comment by kylerc** [comment]
Fixed on dev, just not on live yet
