### ISSUE TITLE
Map icon missing from tournament/match view.

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#338]
<img width="700" alt="screen shot 2018-03-07 at 4 22 11 pm" src="https://user-images.githubusercontent.com/1217271/37121727-b9d48ad0-2223-11e8-9680-6dd4591e845e.png">

@Ian-Hitt not sure if you have this variable, but its just missing so it looks funny.

**Comment by Ian-Hitt** [comment]
This is already done
