### ISSUE TITLE
Stats on leagues cards not accurate

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#343]
<img width="381" alt="screen shot 2018-03-08 at 8 35 04 am" src="https://user-images.githubusercontent.com/1217271/37156418-aae3779c-22ab-11e8-9262-dcecc3a0cfe9.png">

Says 0 teams, but if you click on it and go to teams it has 20ish

**Comment by JakeBooher** [comment]
#319
