### ISSUE TITLE
/tournaments: recent tab doesn't show latest tournaments

### ISSUE THREAD

**Issue by nikkiradloff** [BattlePro/battlepro-issues#344]
https://www.battlepro.com/tournaments/?type=recent

**Comment by nikkiradloff** [comment]
same goes for https://www.battlepro.com/matches/?type=recent

**Comment by JakeBooher** [comment]
Are there any completed tournaments? This will only show tournaments with a status of `2`

**Comment by nikkiradloff** [comment]
Ah I'll complete a couple matches/tournaments to confirm

**Comment by nikkiradloff** [comment]
Well will actually need to wait until latest push since I can't input all scores for a bracket.
