### ISSUE TITLE
Notification To Join Team

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#348]
When a user is invited to a team (invite only), the user does not receive any notifications for this invitation.  They only way for a team member to view this invitation is by visiting the team page and clicking 'accept invitation'.  We need to have more methods in place that makes acceptance easier to find.  Something immediately visible when the user logs into their account.

Join Team:
![join team](https://user-images.githubusercontent.com/6005869/37168142-ed8967ac-22d1-11e8-9e4d-11f1f467fcb7.JPG)

**Comment by JakeBooher** [comment]
Is it creating an empty alert, or just nothing at all? From what I can see it should still be creating the alert

**Comment by JakeBooher** [comment]
Just gave it a quick test and it seems the alert is created correctly:

<img width="1058" alt="screen shot 2018-03-08 at 12 18 41 pm" src="https://user-images.githubusercontent.com/179180/37168563-e17ad876-22ca-11e8-8a20-39d794cf9ebd.png">

**Comment by kylerc** [comment]
It looks like this is working, but if there's an issue reopen this @NikAlexander
