### ISSUE TITLE
What Are The Plus Signs For?

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#360]
I noticed new 'plus' signs on the homepage next to article titles.  What are these for?

![capture](https://user-images.githubusercontent.com/6005869/37174703-510827a6-22e5-11e8-81c4-29d2a433055c.jpg)

**Comment by nikkiradloff** [comment]
That's odd. Not seeing them on my end.

**Comment by Ian-Hitt** [comment]
@NikAlexander that is to add a category, for admins only.

**Comment by NikAlexander** [comment]
Strange, I'm not able to edit this or type in a category name.  Here are the categories we need:

- NEWS
- TOURNAMENT
- SITE UPDATE

Not able to modify or change anything here:
![capture](https://user-images.githubusercontent.com/6005869/37177797-80649f62-22ee-11e8-8f84-94b404387aa0.JPG)
  It would be much better to set the category while in edit mode for the thread.  If a tournament is featured to the homepage it should be labelled automatically.

**Comment by mikecreuzer** [comment]
The bug with not being able to modify can look into, but the actual system here was based on XenPorta. We used an existing news source (though we've modified it heavily) and if it doesnt offer this could be tough to port over.

**Comment by Ian-Hitt** [comment]
The issue is that no categories are created in the ACP yet.
