### ISSUE TITLE
Change Tournament Image Icon

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#361]
Simple styling adjustment:

- Change tournament image icon to the image provided below.  Sorry for the low resolution, perhaps @nikkiradloff can help with this.

![capture](https://user-images.githubusercontent.com/6005869/37175343-3d39d844-22e7-11e8-964f-b904e9e72ed4.JPG)

**New Image Icon:**
![trophy](https://user-images.githubusercontent.com/6005869/37175349-415ed73a-22e7-11e8-98fb-e0fff501f15b.png)

**Comment by nikkiradloff** [comment]
@NikAlexander we'll want to avoid loading in one custom icon. We are a little limited by the iconset but it does offer more options such as below. If there's a different one you prefer, we can switch that out.

<img width="271" alt="screen shot 2018-03-15 at 1 20 52 pm" src="https://user-images.githubusercontent.com/15836402/37483150-bbeeb5f8-2853-11e8-9433-4da96f48ea66.png">

**Comment by NikAlexander** [comment]
I guess we can save this as a future fix.  I'm not sure why we can't load in our own icons.  What system are we using that only permits us to select from the options above?

**Comment by Ian-Hitt** [comment]
@NikAlexander It has nothing to do with being limited, rather just a best practice. Every single icon on the site is specifically made to be cohesive, while the icon you uploaded is not uniform with any other icon on the site, making it a bad choice for an icon.
