### ISSUE TITLE
Do Not Require Org Selection When Creating Team

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#369]
When users create a team, the first menu that appears is an organization selection.  This menu appears to all users, even if they have not created an organization.  The presentation quality of the creation process is now convoluted.  To simplify, users should be able to link their organizations to their teams on the following menu or later once created in team settings.

![org](https://user-images.githubusercontent.com/6005869/37256344-9639a75e-252f-11e8-8929-969cb342bd49.JPG)

**Comment by JakeBooher** [comment]
Ah yeah, this definitely isn't supposed to show up if you don't have an organization already
