### ISSUE TITLE
Change Team Wallpaper Dimensions

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#371]
When creating a new team, users are asked to provide images sized: 1440 x 310.  While this is fine on its own, it would be better if we changed dimensions to standard of twitter so that teams can simply place their twitter media on BattlePro.  This makes the team creation process slightly easier since it cuts out the need for specific artwork to be made for teams with twitter accounts.

![team wallpaper](https://user-images.githubusercontent.com/6005869/37256586-4680574a-2533-11e8-9080-6600c1aea446.JPG)

**Solution**:

- [ ] Change create team wallpaper dimensions to 1500 x 500 px

**Comment by JakeBooher** [comment]
@nikkiradloff can you get me a new placeholder image for this?

**Comment by nikkiradloff** [comment]
[bp-placeholder-images.zip](https://github.com/BattlePro/battlepro-issues/files/1816652/bp-placeholder-images.zip)

**Comment by nikkiradloff** [comment]
@JakeBooher if it's easy to switch out, I updated the bg color for all placeholder images
