### ISSUE TITLE
Include this info when creating team for LOL

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#383]
Here is some info that will need to be submitted before entering into a LOL tournament.  I think we should ask for this info when a team is being created for LOL.  If a team is already created and attempting to join a LOL tournament then this info should be submitted.

![league of legends](https://user-images.githubusercontent.com/6005869/37360468-b4bc2fd8-26c6-11e8-8483-a890f052bac9.JPG)

**Comment by JakeBooher** [comment]
This was already completed, we have a page for users to enter their LoL summoner accounts, and it'll block you from joining a tournament until you've entered one for the region specified on the tournament
