### ISSUE TITLE
Avatars not showing in brackets

### ISSUE THREAD

**Issue by nikkiradloff** [BattlePro/battlepro-issues#392]
<img width="868" alt="screen shot 2018-03-15 at 11 45 18 am" src="https://user-images.githubusercontent.com/15836402/37477732-6cad2d9c-2846-11e8-8813-8c904e46ad05.png">
<img width="769" alt="screen shot 2018-03-15 at 11 45 24 am" src="https://user-images.githubusercontent.com/15836402/37477735-6e886ae6-2846-11e8-9342-e2a1e4367b81.png">

**Comment by JakeBooher** [comment]
@kylerc full team objects are available, just need to display the avatar

**Comment by kylerc** [comment]
Was an issue with solo tournaments.  Fixed in next push.
