### ISSUE TITLE
Map picker limit LoL to one map

### ISSUE THREAD

**Issue by kylerc** [BattlePro/battlepro-issues#395]
Needed for match creation with LoL API

**Comment by NikAlexander** [comment]
I'm not sure because I don't follow this title at all but do they really just play one map for events?  Seems kind of limiting in my opinion.

Perhaps they use a different map in later stages of a tournament?

**Comment by kylerc** [comment]
@NikAlexander For competitive LoL I'd say about 95% of it occurs on Summoners Rift.  There are some tournaments that will happen on the other two maps but these are generally pretty specialized and a lot less common.  I don't think I've ever seen a tournament switch maps part of the way through though.  The advantage of limiting to one map is that the LoL API will automatically configure the map and draft type for all games it creates which makes for a pretty streamlined process for players.

**Comment by kylerc** [comment]
Changed in next push
