### ISSUE TITLE
Image not displaying for news article, tournament slider should say 'view tournament' not 'view game'

### ISSUE THREAD

**Issue by nikkiradloff** [BattlePro/battlepro-issues#403]
<img width="807" alt="screen shot 2018-03-22 at 1 04 53 pm" src="https://user-images.githubusercontent.com/15836402/37789371-b4995a28-2dd1-11e8-8cd4-63ddc6afc386.png">

**Comment by nikkiradloff** [comment]
mask is also 1px off
<img width="322" alt="screen shot 2018-03-22 at 1 07 30 pm" src="https://user-images.githubusercontent.com/15836402/37789477-02e1d110-2dd2-11e8-8092-d22cf6f903a7.png">

**Comment by Ian-Hitt** [comment]
@nikkiradloff that article does not have an image is all.
