### ISSUE TITLE
Finished match/tournament not showing in 'past' tab

### ISSUE THREAD

**Issue by nikkiradloff** [BattlePro/battlepro-issues#406]
https://www.battlepro.com/matches/hots-royal-showdown.18/view
https://www.battlepro.com/tournaments/rocket-league-1v1-solo-tournament.42/view

https://www.battlepro.com/matches/?type=recent
https://www.battlepro.com/tournaments/?type=recent

**Comment by kylerc** [comment]
Thanks for the bug report, fixed now :).
