### ISSUE TITLE
Player count error when joining a tournament

### ISSUE THREAD

**Issue by nikkiradloff** [BattlePro/battlepro-issues#408]
Directed to select 5 players. I submit with 5 players and get an error that I didn't select 5. I unselect everything and re-check players and then goes through.

**Comment by kylerc** [comment]
@nikkiradloff I can't seem to replicate this.  To help narrow things down, were there exactly 5 players on the team?  Was this for LoL or some other game?

**Comment by nikkiradloff** [comment]
In that particular case, there were 6 members on the team trying to join a LoL tournament. I was prompted to check which players and selected 5. I'll try to capture a GIF next time I encounter it.

**Comment by kylerc** [comment]
I think this was related to the other player issue.  Reopen if you see it again once the update is deployed though.
