### ISSUE TITLE
Brackets have different content container than rest of tabs

### ISSUE THREAD

**Issue by nikkiradloff** [BattlePro/battlepro-issues#410]
<img width="2310" alt="screen shot 2018-03-27 at 2 04 02 pm" src="https://user-images.githubusercontent.com/15836402/37989018-e07a05a8-31c7-11e8-83c5-61ced92125af.png">
<img width="2310" alt="screen shot 2018-03-27 at 2 04 19 pm" src="https://user-images.githubusercontent.com/15836402/37989019-e1fbd686-31c7-11e8-84ca-34d61b3841f5.png">

**Comment by kylerc** [comment]
This is somewhat intentional since brackets can be quite large so I figured it might be better to show as much of them as possible.  But not every bracket is large enough to need the extra space so not sure what's best here.
