### ISSUE TITLE
Past tournament tags should say 'ended' or 'finished' instead of 'started'

### ISSUE THREAD

**Issue by nikkiradloff** [BattlePro/battlepro-issues#420]
<img width="1269" alt="screen shot 2018-03-28 at 9 11 45 am" src="https://user-images.githubusercontent.com/15836402/38034560-2c98e918-3268-11e8-90d2-7c724adec384.png">

**Comment by kylerc** [comment]
@nikkiradloff good catch, Will be fixed in the next deploy
