### ISSUE TITLE
Edit Match Time

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#427]
Tom Butler from Pro Battle League (PBL) has been having trouble with our matches functionality and moved his operations over to BattleFy due to some of the struggles he's encountered.  I want to fix this as soon as possible to allow him to continue hosting matches on BP since he's been so supportive of our platform.  Its really important for the site to look like its in use and he was the leading participant for that. 

He would like to edit 'match time' because he had trouble having teams show up on time and needed to make adjustments.  Players wouldn't show when they said they would and they needed to make adjustments to the match times.  

**Solutions:**
- Create ability to edit the match info on day of the match
- Allow match details to be changed even if both teams accept it
- Ability to display time zones for match time

Here is the transcript from Tom, perhaps you can come up with other solutions for him:
![move match](https://user-images.githubusercontent.com/6005869/41081105-d40de632-6a29-11e8-8bb6-95048bbdcccf.JPG)

**Comment by JakeBooher** [comment]
> Create ability to edit the match info on day of the match

I've implemented this for matches only, unfortunately we can't really support something like this currently for tournaments as too many other things rely on this start date (stages, etc)

> Ability to display time zones for match time

Unfortunately, like I mentioned before XenForo doesn't support this. What I was able to do, however, is add a notice into the footer that shows the timezone being used with a link to change the timezone for your account:

`All times are displayed in CDT (GMT-05:00). You can change your timezone here.`
