### ISSUE TITLE
Landing Page Background Image

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#50]
Was looking through some old concepts today and found something I really liked for our background.  I'm not fond of our current background because there's too much stark contrast between the black sky and the light blue planet.  There are also too many colors and the old concept art is very cohesive, colors blend in with others.  

- Change background image to old concept art
![landingpage](https://user-images.githubusercontent.com/6005869/29297156-f9c3e71e-812c-11e7-8ce4-081a3cf05fc7.jpg)

**Comment by nikkiradloff** [comment]
![bp-index-header](https://user-images.githubusercontent.com/15836402/30438494-f74eb6f4-9936-11e7-96c5-a3ee15bfe843.jpg)
