### ISSUE TITLE
Tournament Info Not Visible on User Profile Page

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#52]
When creating a tournament, managers should be able to save drafts, which it appears they do.  However, there is no way of accessing these drafts and updating them.  

After publishing a tournament, I am unable to view the event on my user profile page:
![z](https://user-images.githubusercontent.com/6005869/29753592-8a38c8d6-8b42-11e7-8d86-42ad5b701066.JPG)
The only way to view previously created tournaments is to hover over the profile name (top right) and wait until the drop down menu displays 'my events'.
![myevents](https://user-images.githubusercontent.com/6005869/29753609-e8b00000-8b42-11e7-8d8b-54f6d0f1f473.JPG)
Not being able to see this information on the user profile page's "EVENTS" section is misleading.  We don't want people to think that their tournament was NOT saved.

**Comment by JakeBooher** [comment]
The 'events' tab on the user profile is there to list tournaments a user is registered for, or has participated in rather than tournaments that a user has hosted. The "My Events" page is the correct place to find events that you are hosting
