### ISSUE TITLE
Tournaments/Matches: Map picker UI

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#53]

**Comment by NikAlexander** [comment]
**Current UI for reference:**
![mappicker](https://user-images.githubusercontent.com/6005869/29745616-ae899af4-8a8d-11e7-9645-84c2bbc429c1.jpg)

**Comment by nikkiradloff** [comment]
Sketch file:
[battlepro_wrapper.sketch.zip](https://github.com/BattlePro/battlepro-issues/files/1303552/battlepro_wrapper.sketch.zip)

**Comment by nikkiradloff** [comment]
Map wireframe:
https://projects.invisionapp.com/freehand/document/t8Z0UIeqb

**Comment by nikkiradloff** [comment]
Just waiting on @NikAlexander for any feedback or changes

**Comment by nikkiradloff** [comment]
We're moving forward with the UI set out already in the wireframe and there can be adjustments later @Ian-Hitt so can tackle whenever you're able to.
