### ISSUE TITLE
Full list of supported games

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#6]
We will need a list of all platforms/games, since it may have updated

- [ ] Regions
- [ ] logo (svg)
- [ ] banner
- [ ] brand color (at least one for now is fine)
- [x] Party

**Comment by NikAlexander** [comment]
**Featured Games (large image icons):**
- League of Legends (Select A Region) 
- Halo 5 (Xbox One)
- Dota 2 (Select A Region)
- CS:GO (Select A Region)
- Overwatch (Xbox One, Playstation 4, PC)
- Call of Duty Modern Warfare (remastered) (Xbox One, Playstation 4)
- Call of Duty Infinite Warfare (Xbox One, Playstation 4)
- Rocket League (Xbox One, Playstation 4, PC)
- Super Smash Bros. (Wii U)

**League of Legends Regions:**
- North America
- EU West
- EU Nordic & East
- Russia
- Brazil
- Latin America North
- Latin America South
- Japan

**Dota 2 Regions:**
- North America
- South America
- Europe East
- Europe West
- Russia
- Asia
- Oceania

**Other Supported Games:**
- Hearthstone
- Heroes of the Storm
- Doom
- Gears of War 3
- Gears of War 4
- Call of Duty: Black Ops III
- Call of Duty: Ghosts
- Halo: Combat Evolved
- Halo 2
- Halo 3
- Halo 4
- Halo Reach

**Comment by NikAlexander** [comment]
Visual Style Preference:
![featured games](https://user-images.githubusercontent.com/6005869/28980555-4018e412-791c-11e7-9108-f1b5be442426.JPG)
source: [battlefy](www.battlefy.com)

**Comment by Ian-Hitt** [comment]
@JakeBooher  Need to update how we do regions. Before we assumed all regions were always available. Need to be able to set which regions for which games

**Comment by nikkiradloff** [comment]
[bp-game-logos-images.zip](https://github.com/BattlePro/battlepro-issues/files/1307209/bp-game-logos-images.zip)

**Comment by Ian-Hitt** [comment]
@mikecreuzer  We need to have a discussion as to how we are handling game logos, as well as the game chooser for creating tournaments. Putting this momentarily on hold.

**Comment by Ian-Hitt** [comment]
@nikkiradloff Games images are required to be 1170px x 250px per Jakes add-on it would appear. Can you please re-do and send again?

**Comment by nikkiradloff** [comment]
@Ian-Hitt 1170px x 250px is for banners. That aspect ratio doesn't work with the game chooser images. The current images on the demo say 600 x 300.

**Comment by mikecreuzer** [comment]
Nice

**Comment by nikkiradloff** [comment]
[bp-game-images-updated.zip](https://github.com/BattlePro/battlepro-issues/files/1338399/bp-game-images-updated.zip)

**Comment by nikkiradloff** [comment]
<img width="1166" alt="screen shot 2017-09-27 at 11 41 21 am" src="https://user-images.githubusercontent.com/15836402/30932122-27fa1500-a38c-11e7-949e-925128d02854.png">
