### ISSUE TITLE
'Tournament Name' font size and case style change

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#60]
When creating a new tournament, the importance of submitting a tournament name is not visually equal to the other required information.  Suggest that the text for 'Tournament Name' be brought to the same formatting as 'PLATFORM', 'TOURNAMENT TYPE', etc.

![capture](https://user-images.githubusercontent.com/6005869/29754147-4a2664a0-8b4d-11e7-8ae7-fe08dfffec2b.JPG)

**Comment by Ian-Hitt** [comment]
@NikAlexander  This would be inconsistent. It may have more importance, but the heading styling is reserved for section of inputs, not singular inputs. I believe that this should be left as is.
