### ISSUE TITLE
Create More Options for 'Best of' Selection

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#61]
There's currently no way of creating a tournament scenario where 'Best of 3' is used for qualifier matches and 'Best of 5' for the quarter finals or finals.  Staging needs to be set up in a way to provide this level of control to tournament organizers.

**Example:**
- **Finals**: 2 teams left  (Best of 7)
- **Semifinals**: 4 teams left  (Best of 5)
- **Quarterfinals**: 8 teams left (Best of 5)
- **Qualifying Rounds**: Total No. of Teams (Best of 3)

**Current Setup:**
![bestof5](https://user-images.githubusercontent.com/6005869/29754362-72af96e0-8b51-11e7-8160-437165fd16c9.JPG)

**Comment by kylerc** [comment]
@NikAlexander Ya the easiest way we'll be able to support this is with multiple stages.  Our current work on multiple stages will allow for this though :).

**Comment by kylerc** [comment]
This isn't actually finished yet, but since it will be once other issues are fixed ( #165 and #153 mostly) going to close this to shorten the list of issues a bit.
