### ISSUE TITLE
Teams Pending Approval For Tournaments

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#64]
All teams that join a tournament are placed in 'pending approval' status.  There is no visible way for tournament organizers to "approve" teams.  There is no notification what 'pending teams' means to users or how to resolve the issue.

**Note:**
_Pending Teams require the captain to invite more players to their team to complete registration.  However, some of the teams signed up for [ForgeHub's 2v2 Tournament](https://www.battlepro.com/tournaments/forgehub-2v2-throwdown.13/view) fulfill the required amount of players per team._

![capture](https://user-images.githubusercontent.com/6005869/29802714-1d2666fa-8c45-11e7-9f1d-d5767226ea15.JPG)

Below you can see that team '[smelly feet](https://www.battlepro.com/teams/smelly-feet.28/view)' has the required 2 players on their team and is still listed as 'pending approval' status.
![teama](https://user-images.githubusercontent.com/6005869/29826581-9f93963e-8ca5-11e7-9c79-b4a7ea882378.JPG)

**Comment by mikecreuzer** [comment]
@JakeBooher this is stopping people from participating in an active tournament

**Comment by JakeBooher** [comment]
This whole system is being reworked so I'm going to close this
