### ISSUE TITLE
Replace banner placeholder image

### ISSUE THREAD

**Issue by nikkiradloff** [BattlePro/battlepro-issues#70]
![banner_placeholder](https://user-images.githubusercontent.com/15836402/29795387-aa509728-8c11-11e7-86b5-8b154c6bd58d.png)

**Comment by NikAlexander** [comment]
Also to note there is some confusion on dimensions.  It could be 660 x 330px: https://github.com/BattlePro/battlepro-issues/issues/54

**Comment by nikkiradloff** [comment]
![bp-660x330](https://user-images.githubusercontent.com/15836402/30385500-fea07480-986c-11e7-8843-3edae5519dd3.jpg)
