### ISSUE TITLE
Create Ability to Feature Tournaments

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#71]
Provide staff with the ability to "feature" a tournament if it is open for registration.

Once 'featured', the tournament should be visible on the homepage.

**Comment by JakeBooher** [comment]
For this I believe it's worth noting that the homepage is only visible to guests, so I'm not sure how useful this would be

**Comment by JakeBooher** [comment]
`$upcomingFeaturedTournaments` is now available on the index page @Ian-Hitt

**Comment by Ian-Hitt** [comment]
@NikAlexander do you want to add this as a new section, or replace the current "recent tournaments" section with the "featured recent tournaments"
