### ISSUE TITLE
Change Formatting Structure For Uploading 'Gametypes' 

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#79]
Wen users are uploading gametypes to their tournament it is confusing because these are mixed in with uploading maps.  Maps and modes are two different things, separating them will only bring more clarity to tournament organizers.  

Changes:
- Separate 'GAMETYPES' and 'MAPS' into two sections (see formatting below)
- Allow users to provide download links for gametypes

**Current Format:**
![current](https://user-images.githubusercontent.com/6005869/29804568-5ddffa42-8c51-11e7-9795-33bca058ea5c.JPG)

**Proposed Format:**
![gametype](https://user-images.githubusercontent.com/6005869/29804573-6b734ef2-8c51-11e7-8b83-eb0f39b5a89f.jpg)

**Comment by JakeBooher** [comment]
I believe this view is already in the process of being redesigned by @nikkiradloff

**Comment by nikkiradloff** [comment]
This is addressed in the wireframe. Refer to issue #53
