### ISSUE TITLE
Nicer login screen

### ISSUE THREAD

**Issue by mikecreuzer** [BattlePro/battlepro-issues#8]
https://www.battlepro.com/tournaments/add

This could use some nicer, modernizations in design. 

- [ ] Make login trigger a page, not a modal
- [ ] Some kind of login wrapper, icons would be nice
- [ ] Remove extended footer
- [ ] Remove breadcrumb
- [ ] Remove titlebar
- [ ] Some copy on the right side featuring 3 reasons to join

**Comment by mikecreuzer** [comment]
Copy titles could be like "Battle your friends" "Join a team" "Access to community features"

**Comment by Ian-Hitt** [comment]
@mikecreuzer is "Nicer login screen" referring to a different issue than the comment you wrote?
