### ISSUE TITLE
Case Error For 'Create New Team'

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#81]
Case error for 'Create New Team' - the 'N' and 'T' should be capitalized.
Location: [My Accounts Page](https://www.battlepro.com/account/my-accounts)

![create](https://user-images.githubusercontent.com/6005869/29805410-b3246226-8c57-11e7-9a3c-78a46afafc9f.JPG)

**Comment by Ian-Hitt** [comment]
@NikAlexander  All buttons are all upper case by design.

**Comment by Ian-Hitt** [comment]
<img width="373" alt="screen shot 2017-09-14 at 11 08 37 am" src="https://user-images.githubusercontent.com/15836384/30440750-10c25626-993d-11e7-8521-0f6f0e1ed983.png">
