### ISSUE TITLE
Allow Teams To Have Both 'Invites' and 'Applications'

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#83]
Currently teams must decide between 'invites', 'applications' or 'open'.  There is no way for a team to accept applications AND send invites to their friends.  This process seems too limited, I want teams to be flexible to make these choices later.  Perhaps they will lose a team member unexpectedly and need to accept applications?

![invite apply](https://user-images.githubusercontent.com/6005869/29805754-a0d523a6-8c59-11e7-820b-393b7f179fa2.JPG)

**Comment by JakeBooher** [comment]
I believe if you select "Application Only" it'll allow someone with appropriate permissions to invite a user, will confirm this though.

**Comment by JakeBooher** [comment]
Okay, have just confirmed that all of the team types support invitations so this should be good to go
