### ISSUE TITLE
Create 'My Teams' Section on 'Teams' Page

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#92]
If a user has a team and wants to view it, perhaps they click on the '[Teams](https://www.battlepro.com/teams/)' tab at the top of the page.  When a user visits the '[Teams](https://www.battlepro.com/teams/)' page, their team is not clearly visible.  Users must access their team page through the user profile drop down menu and visit '[My Accounts](https://www.battlepro.com/account/my-accounts)'.

Enhancement:
- Create 'My Teams' section on the 'Teams' page.

Teams Page:
![capture](https://user-images.githubusercontent.com/6005869/29887111-5d3d8f5c-8d8a-11e7-8e30-1f280194af83.JPG)

**Comment by Ian-Hitt** [comment]
{$myTeams} is null, and the route for teams/my-teams just loops through {$teams}, which is what the teams page is already doing.

**Comment by Ian-Hitt** [comment]
@NikAlexander For this did you want a link to the My Teams page, or did you want to add an additional table for My Teams above the current table? I agree that you should be able to access your teams from this page, but it is not the main function of the page. A button to view your teams might better serve the purpose, as it does not distract you from the actual purpose, which is to find teams.

**Comment by JakeBooher** [comment]
Page is setup, needs better formatting for headings
