### ISSUE TITLE
Tournaments Disappear When They Start

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#95]
When a tournament eventually reaches its 'start time', it will disappear and no longer be visible on the tournaments listing page.  The tournament doesn't disappear completely, it is only removed from visibility. This will make the tournament EXTREMELY difficult to find unless players saved the link to the tournament and entered it into their browser.  

Repro:
1. Create a new Tournament (Halo, 2 players per team, wager)
2. Set the start time to be very close to current time (must be in future)
3. Once start time is reached, refresh the Tournaments page (for Halo) and notice the tournament has disappeared.

Note:
Here is the link to the expired tournament I created: [Test 2v2 Tournament](https://www.battlepro.com/tournaments/test-2v2-tournament.19/view)

Image shows that '[Test 2v2 Tournament](https://www.battlepro.com/tournaments/test-2v2-tournament.19/view)' is no longer listed:
![test tourney dissappear](https://user-images.githubusercontent.com/6005869/29902036-9df422c4-8dc9-11e7-93e9-afc99917172f.JPG)

**Comment by NikAlexander** [comment]
@JakeBooher This issue was actually being investigated mid May, which you replied:

_"The listing was hiding tournaments that had passed the start date.  I’ve changed that up.  It looks like two teams were able to joint he tournament, but it was configured to require approval on registrations and they were never approved."_

I'm not sure why the fix didn't work but hopefully we can get it right this time.  The tournament starts on Saturday, the 2nd.

**Comment by NikAlexander** [comment]
@jakebooher ForgeHub's 2v2 Throwdown Tournament disappeared when the tournament 'started' at 1pm EST on Saturday, Sept 2nd.

https://www.battlepro.com/tournaments/forgehub-2v2-throwdown.13/view-brackets

The bug behaved the same as it did in the past.  Perhaps because we didn't click 'start' button before the tournament start time?  We clicked 'start' later to see if it would make the tournament visible but it didn't work.

**Comment by JakeBooher** [comment]
Tracked this down, when the tournament is set as a single day event the end_date isn't actually used so it defaults to be the same as the start date because it'll just end depending on the schedule, from now on the listing will no longer take end_date into consideration and will only display based on status :)
