### ISSUE TITLE
Confirmation Email Takes Too Long To Send Out

### ISSUE THREAD

**Issue by NikAlexander** [BattlePro/battlepro-issues#96]
When creating a new account on BattlePro, the confirmation email takes longer than normal to be sent out.  15 minutes have already passed and I still haven't received the confirmation email.  If possible, this process should be immediate.  Players attempting to create an account to join a contest at the last minute will be very unsatisfied by this delay.  Teams could potentially be forced to forfeit from a tournament due to this issue.

**Note:**
_Email was eventually delivered however it took just over 15 minutes to send._

![capture](https://user-images.githubusercontent.com/6005869/29902671-81d57df0-8dcd-11e7-8150-9c2960700197.JPG)

**Comment by JakeBooher** [comment]
This is something completely out of our control, you'll need to contact your host regarding this issue
